export const LOAD_ACTIVE_BOOKS_SUCCESS = "LOAD_ACTIVE_BOOKS_SUCCESS";
export const LOAD_ACTIVE_BOOKS_FAILED = "LOAD_ACTIVE_BOOKS_FAILED";

export const LOAD_BOOKS_SUCCESS = "LOAD_BOOKS_SUCCESS";
export const LOAD_BOOKS_FAILED = "LOAD_BOOKS_FAILED";

export const ADD_BOOK = "ADD_BOOK";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILED = "ADD_BOOK_FAILED";

export const UPDATE_READING_TYPE = "UPDATE_READING_TYPE";
export const UPDATE_READING_TYPE_SUCCESS = "UPDATE_READING_TYPE_SUCCESS";
export const UPDATE_READING_TYPE_FAILED = "UPDATE_READING_TYPE_FAILED";
